version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    working_directory: /go/src/github.com/carlpett/terraform-provider-sops
    steps:
      - checkout
      - run: gpg --import test/testing-key.pgp
      - run: make test crossbuild
      - store_artifacts:
          path: terraform-provider-sops
  release:
    docker:
      - image: circleci/golang:1.16
    working_directory: /go/src/github.com/carlpett/terraform-provider-sops
    steps:
      - checkout
      - run: gpg --import test/testing-key.pgp
      - run: make test crossbuild release
      - run:
          name: Trigger Docker Hub automated build
          command: |
            curl -X POST -H "Content-Type: application/json" \
              --data "{\"source_type\": \"Tag\", \"source_name\": \"$CIRCLE_TAG\"}" \
              https://registry.hub.docker.com/u/carlpett/terraform-provider-sops/trigger/$DOCKER_HUB_TRIGGER_TOKEN/
      - store_artifacts:
          path: binaries

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
